// Vaviable; es el lugar dode donde podemos almacenar datos, que se pueden reutilizar en otros lugares

// string; son palabras, numeros, o cualquier otro caracter que se ponen entre comillas, simples o dobles.

// funciones(argumentos); un conjunto de instrucciones que realiza una tarea o calcula un valor, 
// para que un procedimiento califique como función, debe tomar alguna entrada y devolver una
 //salida donde hay alguna relación obvia entre la entrada y la salida. Para usar una función, 
 //debes definirla en algún lugar del ámbito desde el que deseas llamarla.

 //declaracion; Una ifdeclaración acepta una expresión con un conjunto de paréntesis:
// . Si la expresión se evalúa como un valor verdadero, entonces se ejecuta el código dentro de su cuerpo de código.

// .Si la expresión se evalúa como un valor falso, su cuerpo de código no se ejecutará.

// valores booleanos; Los booleanos son un tipo de datos primitivo. Pueden ser trueo o false.



